image: 3.9-bullseye

pages:
  stage: deploy
  script:
  - curl -sSL https://install.python-poetry.org | python3 -
  - poetry install
  - cd docs
  - make html
  - cp build/html/* ../public
  artifacts:
    paths:
    - public
  only:
  - master
