image: 3.9-bullseye

pages:
  stage: deploy
  script:
  - pip install -U sphinx sphinx-rtd-theme pyment m2r2
  - cd docs
  - make html
  - cp build/html/* ../public
  artifacts:
    paths:
    - public
  only:
  - master
